export const a1Topics = [
	{
		num: "01",
		title: "Noun Gender",
		tag: "foundation",
		important: true,
		preview: "Every noun is masculine or feminine.",
		details: [
			"-o → masculine",
			"-a → feminine",
			"-ción / -dad → feminine",
			"Common exceptions: mano, día",
		],
		path: "noun-gender",
	},
	{
		num: "02",
		title: "Singular & Plural",
		tag: "morphology",
		important: true,
		preview: "Make nouns plural and match articles.",
		details: ["libro → libros", "ciudad → ciudades"],
		path: "singular-plural",
	},
	{
		num: "03",
		title: "Articles (el, la, un, una)",
		tag: "articles",
		important: true,
		preview: "Articles must match the noun's gender.",
		details: ["el / la", "los / las", "un / una"],
		path: "article",
	},

	{
		num: "04",
		title: "Adjective",
		tag: "morphology",
		important: true,
		preview: "Adjectives must match gender and number.",
		details: ["chico alto / chica alta", "libros rojos"],
		path: "adjective",
	},
	{
		num: "05",
		title: "Subject Pronouns",
		tag: "foundation",
		important: true,
		preview: "Who is doing the action.",
		details: ["yo, tú, él, ella", "nosotros/as", "ellos/as", "Often dropped"],
		path: "pronouns",
	},
	{
		num: "06",
		title: "Basic Sentence Structure",
		tag: "syntax",
		important: true,
		preview: "Combine words into simple sentences.",
		details: ["Yo como pan", "Ella bebe agua"],
		path: "/a1/grammar/sentence-structure",
	},
	{
		num: "07",
		title: "Demonstratives (this/that)",
		tag: "reference",
		important: false,
		preview: "Point to things: this, that, these.",
		details: ["este, ese", "esta, esa", "esto, eso"],
		path: "/a1/grammar/demonstrative",
	},
	{
		num: "08",
		title: "Possessive Adjectives",
		tag: "ownership",
		important: false,
		preview: "Show ownership: my, your, his.",
		details: ["mi, tu, su", "nuestro/a"],
		path: "/a1/grammar/possessive-adjectives",
	},
	{
		num: "09",
		title: "Verb 'Ser' (to be)",
		tag: "verbs",
		important: true,
		preview: "Used for identity and description.",
		details: ["soy, eres, es", "Soy estudiante"],
		path: "/a1/grammar/ser",
	},
	{
		num: "10",
		title: "Verb 'Estar' (to be)",
		tag: "verbs",
		important: true,
		preview: "Used for state and location.",
		details: ["estoy, estás, está", "Estoy cansado"],
		path: "/a1/grammar/estar",
	},
	{
		num: "11",
		title: "Verb 'Tener' (to have)",
		tag: "verbs",
		important: true,
		preview: "Express possession, age, and basic needs.",
		details: ["tengo, tienes, tiene", "Tengo 20 años", "Tengo hambre"],
		path: "/a1/grammar/tener",
	},
	{
		num: "12",
		title: "Verb 'Gustar'",
		tag: "verbs",
		important: true,
		preview: "Express likes in a different sentence structure.",
		details: [
			"me gusta",
			"te gusta",
			"le gusta",
			"me gustan libros",
			"Me gusta el café",
		],
		path: "/a1/grammar/gustar",
	},
	{
		num: "13",
		title: "Question Words",
		tag: "syntax",
		important: true,
		preview: "Ask basic questions.",
		details: ["¿Qué?", "¿Dónde?", "¿Cuándo?", "¿Por qué?", "¿Cómo?"],
		path: "/a1/grammar/question-words",
	},
	{
		num: "14",
		title: "Negation",
		tag: "syntax",
		important: false,
		preview: "Make negative sentences.",
		details: ["No + verb", "No entiendo"],
		path: "/a1/grammar/negation",
	},
	{
		num: "15",
		title: "Basic Prepositions",
		tag: "daily life",
		important: false,
		preview: "Connect words and show relationships.",
		details: ["en, a, de, con", "en la casa"],
		path: "/a1/grammar/prepositions",
	},
	{
		num: "16",
		title: "Contractions (al, del)",
		tag: "syntax",
		important: false,
		preview: "Combine prepositions with articles.",
		details: [
			"a + el = al",
			"de + el = del",
			"Voy al mercado",
			"Vengo del trabajo",
		],
		path: "/a1/grammar/contraction",
	},
	{
		num: "17",
		title: "Present Tense (Regular Verbs)",
		tag: "verbs",
		important: true,
		preview: "Learn -ar, -er, -ir verb patterns.",
		details: ["hablo, comes, vive"],
		path: "/a1/grammar/regular-verbs",
	},
	{
		num: "18",
		title: "Irregular Verbs (Core)",
		tag: "verbs",
		important: true,
		preview: "Most-used irregular verbs.",
		details: ["ir → voy", "hacer → hago", "venir → vengo"],
		path: "/a1/grammar/irregular-verbs",
	},
];

export const a2Topics = [
	{
		num: "01",
		title: "Preterite Tense",
		tag: "verbs",
		important: false,
		preview: "Completed past actions. Hablé, comí, viví + key irregulars.",
		details: [
			"hablar → hablé, hablaste…",
			"ser/ir → fui, fuiste…",
			"tener → tuve…",
		],
		path: "/grammar/preterite",
	},
	{
		num: "02",
		title: "Imperfect Tense",
		tag: "verbs",
		important: false,
		preview: "Ongoing or habitual past. Contrasts with preterite.",
		details: [
			"hablaba, comía, vivía",
			"era, estaba, tenía",
			"Used for descriptions",
		],
		path: "/grammar/imperfect",
	},
	{
		num: "03",
		title: "Reflexive Verbs",
		tag: "verbs",
		important: false,
		preview: "Subject and object are the same — the action reflects back.",
		details: [
			"me llamo, te llamas",
			"levantarse, ducharse",
			"Always with reflexive pronoun",
		],
		path: "/grammar/reflexive",
	},
	{
		num: "04",
		title: "Direct Object Pronouns",
		tag: "pronouns",
		important: false,
		preview: "Replace the noun receiving the action directly.",
		details: [
			"lo, la, los, las",
			"Lo veo → I see it",
			"Placed before conjugated verb",
		],
		path: "/grammar/direct-pronouns",
	},
	{
		num: "05",
		title: "Indirect Object Pronouns",
		tag: "pronouns",
		important: false,
		preview: "The recipient or beneficiary of the action.",
		details: [
			"me, te, le, nos, os, les",
			"Le doy el libro",
			"Often with dar, decir, mandar",
		],
		path: "/grammar/indirect-pronouns",
	},
	{
		num: "06",
		title: "Comparatives & Superlatives",
		tag: "adjectives",
		important: false,
		preview: "Making comparisons — more than, less than, the most.",
		details: ["más grande que", "menos caro que", "el más grande de todos"],
		path: "/grammar/comparatives",
	},
	{
		num: "07",
		title: "Modal Verbs",
		tag: "verbs",
		important: false,
		preview:
			"poder, querer, deber + infinitive for ability, desire, obligation.",
		details: ["Puedo hablar", "Quiero comer", "Debo estudiar"],
		path: "/grammar/modals",
	},
];
