const numbers = [
	{ n: 0, es: "cero", pron: "seh-ro" },
	{ n: 1, es: "uno", pron: "oo-no" },
	{ n: 2, es: "dos", pron: "dohs" },
	{ n: 3, es: "tres", pron: "trehs" },
	{ n: 4, es: "cuatro", pron: "kwah-tro" },
	{ n: 5, es: "cinco", pron: "seen-ko" },
	{ n: 6, es: "seis", pron: "says" },
	{ n: 7, es: "siete", pron: "syeh-teh" },
	{ n: 8, es: "ocho", pron: "oh-cho" },
	{ n: 9, es: "nueve", pron: "nweh-beh" },
	{ n: 10, es: "diez", pron: "dyehs" },
	{ n: 11, es: "once", pron: "on-seh" },
	{ n: 12, es: "doce", pron: "doh-seh" },
	{ n: 13, es: "trece", pron: "treh-seh" },
	{ n: 14, es: "catorce", pron: "ka-tor-seh" },
	{ n: 15, es: "quince", pron: "keen-seh" },
	{ n: 16, es: "dieciséis", pron: "dyeh-see-says" },
	{ n: 17, es: "diecisiete", pron: "dyeh-see-syeh-teh" },
	{ n: 18, es: "dieciocho", pron: "dyeh-see-oh-cho" },
	{ n: 19, es: "diecinueve", pron: "dyeh-see-nweh-beh" },
	{ n: 20, es: "veinte", pron: "bayn-teh" },
	{ n: 21, es: "veintiuno", pron: "bayn-tyoo-no" },
	{ n: 22, es: "veintidós", pron: "bayn-tee-dohs" },
	{ n: 23, es: "veintitrés", pron: "bayn-tee-trehs" },
	{ n: 24, es: "veinticuatro", pron: "bayn-tee-kwah-tro" },
	{ n: 25, es: "veinticinco", pron: "bayn-tee-seen-ko" },
	{ n: 26, es: "veintiséis", pron: "bayn-tee-says" },
	{ n: 27, es: "veintisiete", pron: "bayn-tee-syeh-teh" },
	{ n: 28, es: "veintiocho", pron: "bayn-tee-oh-cho" },
	{ n: 29, es: "veintinueve", pron: "bayn-tee-nweh-beh" },
	{ n: 30, es: "treinta", pron: "trayn-tah" },
	{ n: 33, es: "treinta y tres", pron: "trayn-tah ee trays" },
	{ n: 37, es: "treinta y siete", pron: "trayn-tah ee syeh-teh" },
	{ n: 40, es: "cuarenta", pron: "kwah-ren-tah" },
	{ n: 42, es: "cuarenta y dos", pron: "kwah-ren-tah ee dohs" },
	{ n: 49, es: "cuarenta y nueve", pron: "kwah-ren-tah ee nweh-beh" },
	{ n: 50, es: "cincuenta", pron: "seen-kwen-tah" },
	{ n: 51, es: "cincuenta y uno", pron: "seen-kwen-tah ee oo-noh" },
	{ n: 56, es: "cincuenta y seis", pron: "seen-kwen-tah ee says" },
	{ n: 60, es: "sesenta", pron: "seh-sen-tah" },
	{ n: 64, es: "sesenta y cuatro", pron: "seh-sen-tah ee kwah-troh" },
	{ n: 68, es: "sesenta y ocho", pron: "seh-sen-tah ee oh-choh" },
	{ n: 70, es: "setenta", pron: "seh-ten-tah" },
	{ n: 74, es: "setenta y cuatro", pron: "seh-ten-tah ee kwah-troh" },
	{ n: 78, es: "setenta y ocho", pron: "seh-ten-tah ee oh-choh" },
	{ n: 80, es: "ochenta", pron: "oh-chen-tah" },
	{ n: 82, es: "ochenta y dos", pron: "oh-chen-tah ee dohs" },
	{ n: 85, es: "ochenta y cinco", pron: "oh-chen-tah ee seen-koh" },
	{ n: 90, es: "noventa", pron: "noh-ben-tah" },
	{ n: 95, es: "noventa y cinco", pron: "noh-ben-tah ee seen-koh" },
	{ n: 98, es: "noventa y ocho", pron: "noh-ben-tah ee oh-choh" },
	{ n: 100, es: "cien", pron: "syen" },
	{ n: 101, es: "ciento uno", pron: "syen-to oo-no" },
	{ n: 200, es: "doscientos", pron: "dos-syen-tos" },
	{
		n: 299,
		es: "doscientos noventa y nueve",
		pron: "dos-syen-tos no-ben-tah ee nweh-beh",
	},
	{ n: 300, es: "trescientos", pron: "tres-syen-tos" },
	{
		n: 399,
		es: "trescientos noventa y nueve",
		pron: "tres-syen-tos no-ben-tah ee nweh-beh",
	},
	{ n: 400, es: "cuatrocientos", pron: "kwah-tro-syen-tos" },
	{
		n: 499,
		es: "cuatrocientos noventa y nueve",
		pron: "kwah-tro-syen-tos no-ben-tah ee nweh-beh",
	},
	{ n: 500, es: "quinientos", pron: "kee-nyen-tos" },
	{
		n: 599,
		es: "quinientos noventa y nueve",
		pron: "kee-nyen-tos no-ben-tah ee nweh-beh",
	},
	{ n: 600, es: "seiscientos", pron: "says-syen-tos" },
	{
		n: 699,
		es: "seiscientos noventa y nueve",
		pron: "says-syen-tos no-ben-tah ee nweh-beh",
	},
	{ n: 700, es: "setecientos", pron: "seh-teh-syen-tos" },
	{
		n: 799,
		es: "setecientos noventa y nueve",
		pron: "seh-teh-syen-tos no-ben-tah ee nweh-beh",
	},
	{ n: 800, es: "ochocientos", pron: "oh-cho-syen-tos" },
	{
		n: 899,
		es: "ochocientos noventa y nueve",
		pron: "oh-cho-syen-tos no-ben-tah ee nweh-beh",
	},
	{ n: 900, es: "novecientos", pron: "no-beh-syen-tos" },
	{
		n: 999,
		es: "novecientos noventa y nueve",
		pron: "no-beh-syen-tos no-ben-tah ee nweh-beh",
	},
	{ n: 1000, es: "mil", pron: "meel" },
];

const yearExamples = [
	{
		n: 1492,
		es: "mil cuatrocientos noventa y dos",
	},
	{ n: 1776, es: "mil setecientos setenta y seis" },
	{ n: 1900, es: "mil novecientos" },
	{ n: 1969, es: "mil novecientos sesenta y nueve" },
	{ n: 2000, es: "dos mil" },
	{ n: 2001, es: "dos mil uno" },
	{ n: 2024, es: "dos mil veinticuatro" },
	{ n: 2500, es: "dos mil quinientos" },
	{ n: 3000, es: "tres mil" },
];

// ── Tabs config — note styles inlined, no lookup object needed ─────────────────

const TABS = [
	{
		id: "0-10",
		label: "0 – 10",
		dot: "bg-[#f59e0b]",
		active: "bg-[#f59e0b] text-[#09090b] border-[#f59e0b]",
		inactive:
			"text-[var(--text-muted)] border-[#27272a] hover:border-[#3f3f46] hover:text-[#71717a]",
		filter: (n) => n >= 0 && n <= 10,
		note: {
			title: "0 – 10 · the core set",
			body: "These are the atoms. Every other number is built from these. Drill them until they're automatic — you'll use them in every compound number.",
			tag: "memorise first",
			cls: {
				wrap: "border-[#f59e0b]/30 bg-[#f59e0b]/5",
				dot: "bg-[#f59e0b]",
				tag: "text-[#f59e0b] border-[#f59e0b]/30 bg-[#f59e0b]/10",
			},
		},
	},
	{
		id: "11-20",
		label: "11 – 20",
		dot: "bg-[#f87171]",
		active: "bg-[#f87171] text-[#09090b] border-[#f87171]",
		inactive:
			"text-[var(--text-muted)] border-[#27272a] hover:border-[#3f3f46] hover:text-[#71717a]",
		filter: (n) => n >= 11 && n <= 20,
		note: {
			title: "11 – 20 · the irregular teens",
			body: "11–15 are completely unique words (once, doce…). 16–19 are fused forms of diez + the unit — written as one word. 20 is veinte, not veintiuno yet.",
			tag: "watch out",
			cls: {
				wrap: "border-[#f87171]/30 bg-[#f87171]/5",
				dot: "bg-[#f87171]",
				tag: "text-[#f87171] border-[#f87171]/30 bg-[#f87171]/10",
			},
		},
	},
	{
		id: "21-29",
		label: "21 – 29",
		dot: "bg-[#a78bfa]",
		active: "bg-[#a78bfa] text-[#09090b] border-[#a78bfa]",
		inactive:
			"text-[var(--text-muted)] border-[#27272a] hover:border-[#3f3f46] hover:text-[#71717a]",
		filter: (n) => n >= 21 && n <= 29,
		note: {
			title: "21 – 29 · veinti- compounds",
			body: "All fused with veinti-. Note: veintiún (before masculine noun), veintiuna (before feminine noun). After 29 the pattern switches — treinta y uno (separate words).",
			tag: "pattern shift at 30",
			cls: {
				wrap: "border-[#a78bfa]/30 bg-[#a78bfa]/5",
				dot: "bg-[#a78bfa]",
				tag: "text-[#a78bfa] border-[#a78bfa]/30 bg-[#a78bfa]/10",
			},
		},
	},
	{
		id: "30-100",
		label: "30 – 100",
		dot: "bg-[#4ade80]",
		active: "bg-[#4ade80] text-[#09090b] border-[#4ade80]",
		inactive:
			"text-[var(--text-muted)] border-[#27272a] hover:border-[#3f3f46] hover:text-[#71717a]",
		filter: (n) => n >= 30 && n <= 100,
		note: {
			title: "31 – 99 · tens + y + unit",
			body: "From 31 onwards: [ten] y [unit]. Treinta y uno, cuarenta y dos… The y (and) is always there. Tens are regular except sesenta (not seisenta) and setenta (not sietenta).",
			tag: "formula: ten + y + unit",
			cls: {
				wrap: "border-[#4ade80]/30 bg-[#4ade80]/5",
				dot: "bg-[#4ade80]",
				tag: "text-[#4ade80] border-[#4ade80]/30 bg-[#4ade80]/10",
			},
		},
	},
	{
		id: "101-999",
		label: "101 – 999",
		dot: "bg-[#38bdf8]",
		active: "bg-[#38bdf8] text-[#09090b] border-[#38bdf8]",
		inactive:
			"text-[var(--text-muted)] border-[#27272a] hover:border-[#3f3f46] hover:text-[#71717a]",
		filter: (n) => n >= 101 && n <= 999,
		note: {
			title: "100 vs 101+",
			body: "Cien is used alone (exactly 100). The moment you go above 100, it becomes ciento — ciento uno, ciento veinte. This is one of the most common mistakes.",
			tag: "cien ≠ ciento",
			cls: {
				wrap: "border-[#38bdf8]/30 bg-[#38bdf8]/5",
				dot: "bg-[#38bdf8]",
				tag: "text-[#38bdf8] border-[#38bdf8]/30 bg-[#38bdf8]/10",
			},
		},
	},
	{
		id: "1000+",
		label: "1000+",
		dot: "bg-[#e879f9]",
		active: "bg-[#e879f9] text-[#09090b] border-[#e879f9]",
		inactive:
			"text-[var(--text-muted)] border-[#27272a] hover:border-[#3f3f46] hover:text-[#71717a]",
		filter: (n) => n >= 1000,
		note: null,
	},
];

export { numbers, yearExamples, TABS };
